title: "Haig Bishop"
description: "A MSc student at the University of Canterbury with a focus on applying computer science to scientific progress."
url: "https://haig.science"
baseurl: ""

# Build settings
theme: minimal-mistakes-jekyll
remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-include-cache

# Sidebar settings
sidebar:
  nav: ""
  sticky: true
  width: "thin"

author:
  name: "Haig Bishop"
  avatar: "/assets/images/haig_portrait.jpg"
  bio: "A MSc student at the University of Canterbury with a focus on applying computer science to scientific progress."
  links:
    - label: "My LinkedIn"
      url: "https://www.linkedin.com/in/haig-bishop-34536a226/"
      icon: "fab fa-linkedin"
    - label: "My GitHub"
      url: "https://github.com/HaigBishop/"
      icon: "fab fa-github"

footer:
  content: "© {{ 'now' | date: '%Y' }} Haig Bishop."

# SEO settings
seo:
  type: "Person"
  name: "Haig Bishop"

# SASS customization
sass:
  custom_styles: "/_sass/custom.scss"

# Exclude unnecessary files
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
