title: "Haig Bishop"
description: "A MSc student at the University of Canterbury with a focus on applying computer science to scientific progress."
baseurl: "" # Leave this empty for user site
url: "https://HaigBishop.github.io" # Your GitHub Pages URL
remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

author:
  name: "Haig Bishop"
  avatar: "/assets/haig_portrait.jpg"
  links:
    - label: "LinkedIn"
      url: "https://www.linkedin.com/in/haig-bishop-34536a226/"
      icon: "fab fa-linkedin"
    - label: "GitHub"
      url: "https://github.com/HaigBishop/"
      icon: "fab fa-github"
