title: "Haig Bishop"
description: "AA MSc student at the University of Canterbury with a focus on applying computer science to scientific progress."
baseurl: "" # Leave this empty for a user site
url: "https://HaigBishop.github.io" # Your GitHub Pages URL
theme: "minimal"
plugins:
  - jekyll-seo-tag

author:
  name: "Haig Bishop"
  avatar: "/assets/images/haig_portrait.jpg"
  links:
    - label: "LinkedIn"
      url: "https://www.linkedin.com/in/haig-bishop-34536a226/"
      icon: "fab fa-linkedin"
    - label: "GitHub"
      url: "https://github.com/HaigBishop/"
      icon: "fab fa-github"

sidebar:
  nav: "sidebar-nav" # Reference to your custom sidebar navigation

sass:
  style: compressed
  load_paths:
    - _sass
custom_css:
  - "/assets/css/custom.css"
